config/routes.rb
Books::Application.routes.draw do
  root 'books#index'

  resources :books do
    collection do
      get 'page/:page', :action => :index
      get 'bargains'
      get 'bargains/page/:page', :action => :bargains
    end

    resources :reviews
    resources :messages
  end


  resources :photos
  devise_for :users
  get 'users',          to: 'users#index',   as: :all_users
  get 'users/:id',      to: 'users#show',    as: :single_user
  get 'users/:id/edit', to: 'users#edit',    as: :edit_user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :book
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_book

  respond_to :html

  def index
    @messages = Message.all
    respond_with(@messages)
  end

  def show
    @message = @book.messages.find(params[:id])
    respond_with @book, @message 
  end

  def new
    @message = @book.messages.new
  end

  def create
    @message = @message.new(message_params)
    respond_with @book, @review  do |format|
      if message.save
        flash[:notice] = 'Beskeden er oprettet!' unless request.xhr?
      else
        format.html { render 'new', status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    def message_params
      params.require(:message).permit(:content, :user_id, :reciever_id, :book_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for([@book, @message], remote: true, authenticity_token: true,  html:{class:'form-horizontal'} ) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <%= render 'shared/errors', object: @message %>
      </ul>
    </div>
  <% end %>

  <p>
  <%= bootstrap_form_field(f, :content) do %>
    <%= f.text_area(:content, size: "50x6") %>
  <% end %>
  </p>
  <p style="margin-left:150px">
    <%= f.submit "Send besked" ,class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Beskeder</h1>

<table>
  <thead>
    <tr>
      <th>Besked</th>
      <th>Bruger</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.user %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<div class="well">
  <%= "Besked til" %> <strong><%= link_to(User.find(@book.user_id).username, single_user_path(@book.user_id))  %></strong>
  <%= render 'form' %>
</div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Besked</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Bruger:</strong>
  <%= @message.user %>
</p>

<%= link_to 'Rediger', edit_message_path(@message) %> |
<%= link_to 'Tilbage', messages_path %>