config/routes.rb
Books::Application.routes.draw do
  root 'books#index'

  resources :books do
    collection do
      get 'page/:page', :action => :index
      get 'bargains'
      get 'bargains/page/:page', :action => :bargains
    end

    resources :reviews
    resources :messages
  end


  resources :photos
  devise_for :users
  get 'users',          to: 'users#index',   as: :all_users
  get 'users/:id',      to: 'users#show',    as: :single_user
  get 'users/:id/edit', to: 'users#edit',    as: :edit_user
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Please correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| -%>
  <div class="alert alert-dismissable alert-<%= key %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= value -%>
  </div>
<% end -%>

app/views/shared/_review.html.erb
<li>
  <% if review.stars.to_i.between?(2,5) %>
    <span class="stars"><%= "#{review.stars} stjerner"  %></span>
  <% elsif review.stars.to_i == 1 %>
    <span class="stars"><%= "#{review.stars} stjerne"  %></span>
  <% end %>
  <br />
  <span class="name">af <%= User.find(review.user_id).email if review.user_id %></span>
  <span class="date text-muted"><%= time_ago_in_words(review.created_at) %> siden</span>
  <blockquote><p><%= review.comment %></p></blockquote>
  <% if user_signed_in? && current_user.id == review.user_id %>
    <span class='inline-button-form'>
      <%= link_to 'Slet', book_review_path(params['id'], review.id), 
            method: :delete, data: {confirm: "Er du sikker?"}, class: 'red'  %>
    </span>
  <% end %>
</li>

app/views/shared/_reviews.html.erb
<ol id="reviews">
  <%= render partial: 'shared/review', collection: reviews %>
</ol>