config/routes.rb
Books::Application.routes.draw do
  root 'books#index'

  resources :books do
    collection do
      get 'page/:page', :action => :index
      get 'bargains'
      get 'bargains/page/:page', :action => :bargains
    end

    resources :reviews
    resources :messages
  end


  resources :photos
  devise_for :users
  get 'users',          to: 'users#index',   as: :all_users
  get 'users/:id',      to: 'users#show',    as: :single_user
  get 'users/:id/edit', to: 'users#edit',    as: :edit_user
end

app/models/book.rb
class Book < ActiveRecord::Base
  GENRES = %w(Fiktion Filosofi Religion Natur)

  validates :title, :abstract, :author, :pages, :price, :genre, presence: true

  validates :abstract, length: { minimum: 15 }, unless: 'abstract.blank?'

  validates :pages,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 },
            unless: 'pages.blank?'

  validates :price,
            numericality: { greater_than_or_equal_to: 0 },
            if: '!price.blank?'

  validates :genre, inclusion: { in: GENRES }, unless: 'genre.blank?'

  validates :cover, presence: true
  validates_inclusion_of :cover, :in => %w( Paperback Hardcover Læderindbundet )

  scope :bargains, -> { where('price < 10.00') }

  scope :by, ->(author) { where('author = ?', author) }

  has_many :reviews, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :book_photos
  accepts_nested_attributes_for :book_photos, allow_destroy: true

  paginates_per 50

  def average_stars
    if reviews.loaded?
      reviews.map(&:stars).average
    else
      reviews.average(:stars)
    end
  end

  def recent_reviews(recent_count = 5)
    reviews.order('created_at desc').limit(recent_count)
  end

  def self.search(search)
    where("author LIKE ? OR title LIKE ? OR genre LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  respond_to :html, :xml, :json

  before_action :set_book,
                only: [:show, :edit, :update, :destroy]

  before_action :set_specials_flash,
                only: [:index, :bargains]

  def index
    @books = list_books
    if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC")
    end

    respond_with @books
  end

  def bargains
    @books = list_books.bargains
    respond_with @books
  end

  def show
    respond_with @book
  end

  def new
    if user_signed_in?
      @book = Book.new
    else
      redirect_to new_user_registration_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book['user_id'] = current_user.id
    flash[:notice] = "#{@book.title} blev tilføjet med bruger_id #{@book.user_id}!" if @book.save
    respond_with @book
  end

  def edit
  end

  def update
    flash[:notice] = "#{@book.title} blev opdateret!" if @book.update(book_params)
    respond_with @book
  end

  def destroy
    @book.destroy
    redirect_to books_url, alert: "#{@book.title} blev slettet!"
  end

  private

  def set_specials_flash
    flash[:notice] = "Hos Kundskabens Træ finder du bøger til de søgende og dem som elsker viden. "
  end

  def list_books
    Book.includes(:reviews).order(:title).page params[:page]
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def author_search
    @author_books = Book.where(author: params[:author]).order(created_at: :desc)
  end

  def book_params
    params.require(:book).permit(:user_id, :title, :abstract, :author, :pages, 
                                 :price, :genre, :cover, book_photos_attributes: [:id, :photo, :_destroy] )
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def formatted_time(time)
    time.strftime('%B %d, %Y at %l:%M %p')
  end

  # def image_for(book)
  #   file_name = book.image_file_name.blank? ? 'placeholder.png' : book.image_file_name
  #   image_tag(file_name, class: 'img-rounded')
  # end

  def format_average_stars(book)
    average = number_with_precision(book.average_stars, precision: 1)
    if average
      average + ' stjerner'
    else
      content_tag(:span, 'Ingen anmeldelser', { class: 'reviews' })
    end
  end

  def star_pics(avarage)
    if avarage.to_int < 1.5
      content_tag(:span, image_tag('1_star.png', size: "100x30"))
    elsif avarage.to_int > 1.5 && avarage.to_int < 2.5
      content_tag(:span, image_tag('2_star.png', size: "100x30"))
    elsif avarage.to_int > 2.5 && avarage.to_int < 3.5
      content_tag(:span, image_tag('3_star.png', size: "100x30"))
    elsif avarage.to_int > 3.5 && avarage.to_int < 4.5
      content_tag(:span, image_tag('4_star.png', size: "100x30"))
    elsif avarage.to_int > 4.5 
      content_tag(:span, image_tag('5_star.png', size: "100x30"))
    end
  end

end

app/views/books/_average_stars.html.erb
<% if book.reviews.any? %>
  <%= star_pics(book.average_stars)  %>
  ( <%= format_average_stars(book) %> ud af <%= book.reviews.count %> anmeldelser )
<% end %>

app/views/books/_book_photo_fields.html.erb
<div class="nested-fields">
  <%= f.file_field :photo %>
  <!-- link_to_remove_association "remove", f -->
</div>

app/views/books/_form.html.erb
<%= form_for(@book, html:{class: 'form-horizontal', multipart: true}) do |f| %>
  <%= render 'shared/errors', object: @book %>

  <%= bootstrap_form_field(f, "Titel") do %>
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  <% end %>

  <%= bootstrap_form_field(f, "Forfatter") do %>
    <%= f.text_field :author, class: "form-control" %>
  <% end %>

  <%= bootstrap_form_field(f, "Beskrivelse") do %>
    <%= f.text_area :abstract, rows: 5, class: "form-control" %>
  <% end %>

  <%= bootstrap_form_field(f, "Antal sider") do %>
    <%= f.text_field :pages, class: "form-control" %>
  <% end %>

  <%= bootstrap_form_field(f, "Pris") do %>
    <%= f.text_field :price, class: "form-control" %>
  <% end %>

  <%= bootstrap_form_field(f, "Cover") do %>
    <%= f.select :cover, ['Paperback', 'Hardcover', 'Læderindbundet'], { prompt: "Vælg..." }, { class: "form-control" } %>
  <% end %>

  <%= bootstrap_form_field(f, "Genre") do %>
    <%= f.select :genre, Book::GENRES, { prompt: "Vælg..." }, { class: "form-control" } %>
  <% end %>

  <%#<%= bootstrap_form_field(f, "Udgivet") do %>
    <%#<%= f.date_select :published_on,%>
                      <%#{ start_year: 1, prompt: true, order: [ :month, :day, :year ] },%>
                      <%#{ class: "form-control date-select" } %>
  <%#<% end %>
  <% f.fields_for :book_photo do |photo| %>
    <% render 'book_photo_fields', f:photo %>
  <% end %>
  <div class="links"><%= link_to_add_association 'add a photo', f, :book_photos %></div>
  <br>
  <p>
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', @book.id ? book_path(@book) : books_path, class: 'btn btn-link' %>
  </p>
<% end %>

app/views/books/_list.html.erb
<div class="col-sm-2">
  <div class="navigation">
    <ul class="navigation_list">
      <p class="navigation_list_hl">Genrer</p>
      <li><%= link_to 'Alle Bøger', books_path %></li>
      <li><%= link_to 'Filosofi', books_path(search: 'Filosofi') %></li>
      <li><%= link_to 'Natur', books_path(search: 'Natur') %></li>
      <li><%= link_to 'Psykologi', books_path(search: 'Psykologi') %></li>
      <li><%= link_to 'Religion', books_path(search: 'Religion') %></li>
      <li><%= link_to 'Fiktion', books_path(search: 'Fiktion') %></li>
      <br />
    </ul>
  </div>
  <%= form_tag(books_path, :method => "get", id: "search-form") do %>
    <div class="search_container">
      <div class="search_icon"><%= image_tag("search.png", size: "50", :alt => "search_icon", :title => "Søg") %></div>
      <div class="search_field"><%= text_field_tag :search, params[:search], placeholder: "Titel, forfatter" %></div>
      <div class="search_btn"><%= submit_tag "Søg" %></div>
      <br>
    </div>
  <% end %>

  <% if @books.present? %>
    <%= render 'books/search_books' %>
  <% else %>
    <% flash[:notice] = "Der var desværre ingen resultater for #{params[:search]}" %>
  <% end %>
</div>

<div class="col-sm-8">
  <div id="books">
  <% books.each_slice(3).to_a.each do |chunk| %>
    <div class="row well" style="padding-left: 125px;">
      <% chunk.each do |book| %>
        <div class="col-sm-4">
        <% if book.book_photos.first.present? %>
          <%= link_to(book) do %>
            <div class="book_cover"><%= image_tag(book.book_photos.first.photo.url(:thumb), alt: 'Billede mangler') %></div>
          <% end %>
        <% else %>
          <%= image_tag('default.png', alt: 'Billede mangler') %>
        <% end %>
          <div class="book_info">
            <%= link_to(truncate(book.title, length: 20), book) %> <br />
            <p class="forfatter">af: <%= book.author.titleize %></p>
            <p class="cover"><%= book.cover %></p>
            <p class="cover"><%= book.price.round %> kr.</p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

<div class="col-sm-2">
</div>

<div class="page_entires_container">
  <div class="pull-left page-entries-info">
  <%# page_entries_info books %>
  </div>

  <div class="pull-right">
  <%# paginate books %>
  </div>
</div>

app/views/books/bargains.html.erb
<header>
  <h3>Bargain Books</h3>
</header>

<%= render partial: 'list', locals: { books: @books } %>

app/views/books/edit.html.erb
<div class="row">
  <h2>Editing <%= @book.title %></h2>

  <%= render 'form' %>
</div>

app/views/books/index.html.erb
<header>
  <% if params['search'].present? %>
    <h3 class="books_headline text-center"><%= capitalize_first(params['search']) %></h3>
  <% else %>
    <h3 class="books_headline text-center">Udvalgte bøger</h3>
  <% end %>
</header>

<%= render partial: 'list', locals: { books: @books } %>

app/views/books/new.html.erb
<% if user_signed_in? %>
  <div class="row">
    <h2>Create a New Book</h2>

    <%= render 'form' %>
  </div>
  <% else %>
    <% redirect_to 'sign_in' %>
<% end %>

app/views/books/show.html.erb
<div class="col-sm-2">
  <% if @book.book_photos.first.present? %>
    <aside class="book-cover">
      <%= link_to image_path(@book.book_photos.first.photo.url) do %>
        <div class="book_normal_cover">
          <%= image_tag @book.book_photos.first.photo.url(:normal), alt: 'Cover' %>
        </div>
      <% end %>
    </aside>
  <% end %>
</div>

<div class="col-sm-8">
  <article class="book">
    <header>
      <h2 class="text-primary"><%= @book.title %></h2>
    </header>
    <p>
      <label>Af:</label>
      <%= link_to @book.author, books_path(:search => @book.author) %>
    </p>
    <p><%= @book.abstract %></p>
    <section>
    <br /><br />
    <section>
      <% @book.book_photos.each_with_index do |book_photo, index| %>
        <% if not index == 0 %>
          <%= link_to image_path(book_photo.photo.url) do %>
             <%= image_tag book_photo.photo.url(:thumb), alt: 'Bog udsnit' %>
           <% end %>
         <% end %>
       <% end %>
      </section>
      <br /><br />
      <header><h4 class="text-primary">Detaljer</h4></header>

      <p class="show_book_description pris">
        <%= number_to_currency(@book.price, unit: "DKK", format: "%n %u") %>
      </p>
      &nbsp; | &nbsp;
      <p class="show_book_description">
        <%= link_to @book.genre, books_path(:search => @book.genre) %>
      </p>
      &nbsp; | &nbsp;
      <p class="show_book_description">
        <%= number_with_delimiter(@book.pages) %> sider
      </p>
      &nbsp; | &nbsp;
      <p class="show_book_description">
        <%= @book.cover %>
      </p>
      <br /><br />
      <p>
        <span id="average_review">
            <%= render partial: 'average_stars', locals: { book: @book } %>
        </span>
      </p>
    </section>

      <br />
      <% if user_signed_in? %>
        <ul class="list-inline">
          <!-- single_user_path(@book.user_id) -->
          <li><%= link_to 'Kontakt sælger', new_book_message_path(@book),
                          remote: true,
                          data: { 'update-target' => 'message_form_container' },
                  class: 'btn btn-primary' %>
          </li>
          <li><%= link_to 'Skriv anmeldelse eller kommentar', new_book_review_path(@book),
                            remote: true,
                            data: { 'update-target' => 'review_form_container' },
                    class: 'btn btn-primary' %>
          </li>
        </ul>
        <% end %>
      <div id="review_form_container"></div>
      <div id="message_form_container"></div>

      <br />
    <section>
      <header><h4 class="text-primary">Anmeldelser</h4></header>
      <% if @book.recent_reviews.any? %>
        <%= render partial: 'shared/reviews', locals: { reviews: @book.recent_reviews } %>
        <p>

          <span id="read_reviews">
            <strong><%= link_to "Læs alle kommentarer ( #{@book.reviews.count} )", book_reviews_path(@book) %></strong>
          </span>
        </p>
      <% else %>
        <p>
          Giv den f&oslash;rste kommentar!
        </p>
        <ol id="reviews"></ol>
      <% end %>
    </section>

      <% if user_signed_in? && current_user.id == @book.user_id %>
      <nav id="book-show-buttons">
        <%= link_to 'Rediger', edit_book_path(@book), class: 'btn btn-default' %>
        <span class='inline-button-form'>
          <%= button_to "Slet:  #{@book.title}", @book,
                       method: :delete,
                       data: { confirm: 'Are you sure?' },
                       class: 'btn btn-danger' %>
        </span>
      </nav>
      <% end %>
    </div>
  </article>

<div class="col-sm-2"></div>